server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: backend-logs
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
      filters:
        - name: "label"
          values:
            - "backend=true"
  relabel_configs:
    - source_labels: [__meta_docker_container_name]
      target_label: container
    - source_labels: [__meta_docker_container_id]
      target_label: container_id
    - source_labels: [__meta_docker_container_name]
      target_label: job
  
